const games = [
  '[["bg-blue","bg-yellow","bg-yellow","bg-yellow"],["bg-blue","bg-yellow","bg-blue","bg-blue"],[]]',
  '[["bg-blue","bg-yellow","bg-green","bg-green"],["bg-yellow","bg-blue","bg-yellow","bg-blue"],["bg-green","bg-green","bg-yellow","bg-blue"],[]]',
  '[["bg-blue","bg-yellow","bg-blue","bg-green"],["bg-yellow","bg-green","bg-yellow","bg-blue"],["bg-yellow","bg-green","bg-green","bg-blue"],[]]',
  '[["bg-yellow","bg-green","bg-yellow","bg-blue"],["bg-yellow","bg-blue","bg-green","bg-green"],["bg-green","bg-yellow","bg-blue","bg-blue"],[]]',
  '[["bg-red","bg-green","bg-red","bg-blue"],["bg-blue","bg-yellow","bg-green","bg-green"],["bg-blue","bg-red","bg-yellow","bg-red"],["bg-green","bg-yellow","bg-blue","bg-yellow"],[]]',
  '[["bg-red","bg-blue","bg-green","bg-yellow"],["bg-yellow","bg-yellow","bg-blue","bg-blue"],["bg-green","bg-green","bg-red","bg-green"],["bg-blue","bg-yellow","bg-red","bg-red"],[]]',
  '[["bg-yellow","bg-red","bg-red","bg-green"],["bg-red","bg-blue","bg-yellow","bg-blue"],["bg-blue","bg-yellow","bg-green","bg-green"],["bg-red","bg-yellow","bg-blue","bg-green"],[]]',
  '[["bg-red","bg-blue","bg-yellow","bg-blue"],["bg-blue","bg-blue","bg-red","bg-green"],["bg-red","bg-yellow","bg-yellow","bg-green"],["bg-yellow","bg-green","bg-green","bg-red"],[]]',
  '[["bg-orange","bg-yellow","bg-red","bg-red"],["bg-blue","bg-orange","bg-green","bg-green"],["bg-blue","bg-red","bg-green","bg-orange"],["bg-yellow","bg-orange","bg-red","bg-blue"],["bg-green","bg-yellow","bg-blue","bg-yellow"],[],[]]',
  '[["bg-orange","bg-purple","bg-green","bg-yellow"],["bg-red","bg-blue","bg-blue","bg-orange"],["bg-green","bg-blue","bg-green","bg-purple"],["bg-orange","bg-red","bg-green","bg-blue"],["bg-yellow","bg-yellow","bg-purple","bg-orange"],["bg-yellow","bg-red","bg-purple","bg-red"],[],[]]',
  '[["bg-purple","bg-purple","bg-orange","bg-purple"],["bg-blue","bg-blue","bg-red","bg-blue"],["bg-red","bg-orange","bg-yellow","bg-green"],["bg-green","bg-red","bg-orange","bg-yellow"],["bg-yellow","bg-green","bg-green","bg-orange"],["bg-yellow","bg-purple","bg-red","bg-blue"],[],[]]',
  '[["bg-red","bg-pink","bg-blue","bg-orange"],["bg-pink","bg-orange","bg-purple","bg-green"],["bg-orange","bg-red","bg-pink","bg-yellow"],["bg-purple","bg-green","bg-red","bg-green"],["bg-yellow","bg-blue","bg-yellow","bg-blue"],["bg-green","bg-purple","bg-pink","bg-blue"],["bg-yellow","bg-purple","bg-orange","bg-red"],[],[]]',
  '[["bg-purple","bg-orange","bg-green","bg-blue"],["bg-pink","bg-blue","bg-pink","bg-orange"],["bg-orange","bg-yellow","bg-red","bg-blue"],["bg-red","bg-orange","bg-purple","bg-yellow"],["bg-green","bg-green","bg-purple","bg-yellow"],["bg-purple","bg-green","bg-yellow","bg-blue"],["bg-pink","bg-red","bg-red","bg-pink"],[],[]]',
];
